# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(:mysql, :development, :host) %>
  username: <%= Rails.application.credentials.dig(:mysql, :development, :usr) %>
  password: <%= Rails.application.credentials.dig(:mysql, :development, :pwd) %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: contact_importer_development

test:
  <<: *default
  database: contact_importer_test

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:mysql, :production, :host) %>
  username: <%= Rails.application.credentials.dig(:mysql, :production, :usr) %>
  password: <%= Rails.application.credentials.dig(:mysql, :production, :pwd) %>
  database: contact_importer_production